version: "3"

services:
  db:
    image: postgres:15.2-alpine
    container_name: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  db-store: